export const getUrlData = (urlName) => {
    switch (urlName) {
        case '/by-industry': return { urlsrc: "/service/WebsiteByIndustries.jpg", content: "As an integral facet of our comprehensive suite of services, Enigmatic Ads prides itself on its extensive portfolio, having constructed and sustained websites across a myriad of industries. From tech startups to established enterprises, from healthcare to hospitality, our versatility knows no bounds. Each project is approached with meticulous care and tailored expertise, ensuring that every website we create is not just functional, but truly resonates with its target audience. Our diverse experience equips us with invaluable insights and strategies, enabling us to adapt and excel in any sector. Entrust us to actualize your digital vision, regardless of your industry or niche.", title: "By Industry" };
        case '/by-type': return { urlsrc: "/service/websitebytype.jpg", content: "Enigmatic Ads has built and maintained websites using pretty much every CMS, Site Builder, and Language. Let us know if you don’t see your odds are we have done it! Below is a list of the most frequent.", title: "By Type" };
        case '/custom-plugins': return { urlsrc: "/service/CustomPlugins.jpg", content: "Is your website falling short of expectations? Our adept programmers specialize in crafting tailored experiences that exceed both your and your clients' expectations. Many users of 'template' sites settle for a subpar experience, unaware of the potential for enhancement. The good news? We're here to unlock that potential through meticulous adjustments and optimizations. From refining the user interface to enhancing functionality, we'll transform your website into a standout digital destination. Don't settle for mediocrity when excellence is within reach. Let us elevate your online presence and ensure it aligns perfectly with your vision and objectives.", title: "Custom Plugins" }
        case '/custom-themes': return { urlsrc: "/service/CustomThemes.jpg", content: "Using your website infrastructure of choice, we build themes to look and function exactly as you wish.", title: "Custom Themes" }
        case '/api-integration': return { urlsrc: "/service/ApiIntegration.jpg", content: "Ever wished to integrate your website with external data sources? Imagine displaying movie schedules, MLS listings, or other relevant information seamlessly on your site. How about enabling clients to pay QuickBooks bills directly online? At ENIGMATIC ADS, we specialize in making these connections a reality. Our skilled team can seamlessly integrate your website with various data sources and payment platforms, enhancing functionality and user experience. Whether it's real-time updates or secure transactions, we've got you covered. Let us bridge the gap between your website and external systems, unlocking new possibilities and delivering added convenience for you and your clients.", title: "API Integration" }
        case '/maintenance-plans': return { urlsrc: "/service/MaintenancePlans.jpg", content: " Ensure the longevity and optimal performance of your website with our comprehensive maintenance plan. Our services include regular updates to plugins, themes, and core software to enhance security and functionality. We conduct routine backups to safeguard your data and provide swift restoration in case of emergencies. Our team monitors site performance, uptime, and security, promptly addressing any issues that arise. Additionally, we offer technical support and troubleshooting to keep your website always running smoothly. With our maintenance plan, you can focus on your business while we ensure your online presence remains secure, reliable, and up to date.", title: "Maintainence Plans" }
        case '/employee-plans': return { urlsrc: "/service/EmployeePlans.jpg", content: "When you can have a whole skilled staff for the hours you need filled, there's no reason to recruit an intern without experience.", title: "Employee Plans" };
        case '/content-generation': return { urlsrc: "/service/ContentGeneration.jpg", content: "At Enigmatic Ads, we understand the challenges of consistently creating meaningful content that accurately represents your business and message. Crafting compelling material demands both effort and expertise. Thankfully, our team possesses the necessary skills and knowledge to simplify this process for you. With our experienced personnel and industry insights, we make content creation easy and stress-free. Whether you need captivating copy, engaging visuals, or impactful messaging, we're here to help you effectively communicate your brand identity and connect with your audience. Trust us to transform your ideas into compelling content that resonates with your target market and drives results.", title: "Content Generation" };
        case '/hosting': return { urlsrc: "/service/Hosting.jpg", content: "At ENIGMATIC ADS, we understand that every website is unique, with varying traffic needs and requirements. That's why we offer a range of hosting solutions tailored to suit your specific needs. Whether you're running a personal blog, a small business website, or a large e-commerce platform, we have the perfect hosting plan for you. Our expert team will work closely with you to assess your requirements and recommend the most suitable hosting solution to ensure optimal performance, reliability, and scalability for your website. With our tailored hosting options, you can rest assured that your website is in good hands.", title: "Hosting" }
        case '/go-viral': return { urlsrc: "/service/GoViral.jpg", content: "At ENIGMATIC ADS, we believe that every business possesses unique qualities or offerings that have the potential to captivate audiences and go viral. Our dedicated team specializes in identifying these distinct attributes and transforming them into compelling and shareable content that resonates with your target audience. Through strategic planning, creative ideation, and precise execution, we harness the power of viral marketing to elevate your brand visibility and drive engagement. With our expertise and innovative approach, we make it our mission to uncover your brand's viral potential and turn it into reality, propelling your business to new heights of success.", title: "Go Viral" }
        case '/online-advertising': return { urlsrc: "/service/OnlineAdvertising.jpg", content: "With a deep understanding of website marketing strategies, we know precisely how to promote your website effectively. From identifying key contacts to selecting the most impactful platforms, we've got you covered. By leveraging our expertise, we can steer clear of the experimentation phase altogether, saving you significant sums of money in the process. Our proven methods and targeted approach ensure that your marketing efforts yield maximum results without wasted resources. Trust us to navigate the intricacies of website promotion, delivering a tailored strategy that elevates your online presence and drives success for your business.", title: "Online Advertisement" }
        case '/web-presence': return { urlsrc: "/service/WebPresenceReviews.jpg", content: "At ENIGMATIC ADS, we prioritize the ongoing health and vitality of your website and online presence. Our team conducts regular and thorough assessments to evaluate various aspects of your digital footprint, including website performance, user experience, search engine optimization, and social media presence. Based on these assessments, we develop a comprehensive improvement strategy tailored to address areas of opportunity and enhance your overall online presence. With our proactive approach and strategic insights, we ensure that your website remains optimized, competitive, and aligned with your business goals, driving sustained growth and success in the digital landscape.", title: "Web Presence" }
        case '/custom-business': return { urlsrc: "/service/CustomBusinessSoftware.jpg", content: "Wondering how software can streamline operations and boost efficiency for your company? Look no further! At [Your Company Name], we specialize in developing software solutions tailored to your specific needs. Whether it's automating repetitive tasks, optimizing workflow processes, or enhancing communication channels, we've got you covered. What's more, we can seamlessly integrate these software solutions into your website and ensure compatibility across various devices, making them mobile and app friendly. Let us harness the power of technology to save you time and money while empowering your business to thrive in today's fast-paced digital landscape.", title: "Custom Business Software" };
        case '/online-ticketing': return { urlsrc: "/service/OnlineTicketSystem.jpg", content: "Our proprietary internal business management software keeps track of clients, staff, and projects. You can personalize anything and set timers for everything. Thus, if you believe you are missing too many important billable moments and post-its. For you, this is the ideal resolution. Now make an appointment for a demo.", title: "Online Ticketing Syatem" };
        case '/web-apps': return { urlsrc: "/service/WebApps.jpg", content: "The demarcation between a mere website and a dynamic web application carries substantial weight in the digital realm. When interactivity and functionality surpass the realms of conventional marketing, a web app emerges as the quintessential solution. Esteemed examples of web applications, such as Dropbox, Facebook, Slack, and Zillow, stand as paragons of this distinction. They transcend static content, offering immersive user experiences and multifaceted functionalities. Whether facilitating seamless file sharing, fostering social connections, or streamlining real estate transactions, these web applications epitomize the fusion of innovation and utility, exemplifying the transformative potential inherent in the evolution from website to web app.", title: "Web Apps" }
        case '/android-apps': return { urlsrc: "/service/AndroidApps.jpg", content: "From inception to user download, our journey is a steadfast pursuit. We nurture our ideas, sculpting them through the crucible of creativity, refining them with unwavering determination. Each step is guided by an unwavering commitment to excellence, from conceptualization to execution. We meticulously craft every detail, honing our creation into a polished gem ready for the world to behold. Through challenges and triumphs, we persist, fueled by passion and driven by the desire to bring our vision to life. And when our creation finally graces the digital realm, it stands as a testament to our dedication and perseverance.", title: "Android Apps" }
        case '/ios-apps': return { urlsrc: "/service/iOSApps.jpg", content: "Seeking to propel your business into the digital forefront? Look no further. Our expertise extends beyond mere promises—we possess the capabilities to navigate the intricate terrain of the App Store with finesse. From ideation to implementation, we orchestrate a seamless journey, ensuring your app garners the attention it deserves. Leveraging cutting-edge technologies and industry insights, we craft bespoke solutions tailored to your unique vision and objectives. Whether it's iOS or Android, our adept team stands ready to transform your ideas into tangible realities. Trust us to navigate the complexities of app development, guiding your business towards unparalleled success in the App Store ecosystem.", title: "IOS Apps" }
        case '/social-media': return { urlsrc: "/service/SocialMedia.jpg", content: "What is the difference between Yelp, Google, Instagram, Twitter, and Facebook? They are social networks, yes. These are intended to be SOCIAL in nature. Due to time constraints, most businesses either don't know how to do it all or don't know how to do it correctly to boost reach. You're in luck, though, because we are experts in all of these websites and much more! Simply in need of direction on what to do and how to do it? Sure, we are able to assist with it.", title: "Social Media" }
        case '/photography': return { urlsrc: "/service/Photography.jpg", content: "Our team of expert photographers is capable of Staff Images Product Images Typical Business Stock Images Drone Images plus, additional things", title: "Photography" };
        case '/videos': return { urlsrc: "/service/VideoTransfers.jpg", content: "From daily status updates on facebook to film production quality.  We can do it.", title: "Videos" };
        case '/banner': return { urlsrc: "/service/banner.jpg", content: "We make use of a 13-ounce, premium, heavyweight scrim vinyl banner. Its flat surface ensures optimal printing quality. Signage, trade exhibits, building wraps, billboards, and other applications are common uses for this material.", title: "Banner" }
        case '/stickers': return { urlsrc: "/service/sticker.jpg", content: "We create a wide range of labels and stickers, both permanent and temporary. Tell us what you need, and we'll identify the ideal sticker type and create it just for you.", title: "Stickers" }
        case '/miscellaneous': return { urlsrc: "/service/MiscellaneousProducts.jpg", content: "This is the situation. Millions of different things are possible to design and print. We should be able to. Simply let us know what you need, and we'll let you know how we can assist you.", title: "Miscellaneous Products" }
        case '/video-transfer': return { urlsrc: "/service/VideoTransfers.jpg", content: "The complete service video production staff at Enigmatic Ads is equipped to handle tasks like memory DVDs, special occasion videos, and video transfers. Equipped with top-notch video gear and sophisticated editing tools, our team of videographers can tailor any project to your specifications. At Enigmatic Ads, we convert all of your home videos and pictures to digital format so that you can enjoy, share, and watch them on any contemporary gadget.", title: "Video Transfer" }
        case '/seo': return { urlsrc: '/service/seo.jpg', content: 'In the realm of SEO, content reigns supreme. High-quality, relevant, and authoritative content not only attracts organic traffic but also earns backlinks and social shares, signaling to search engines that the website is a valuable resource for users. Content should be tailored to meet the needs and interests of the target audience, provide answers to their questions, and offer solutions to their problems. From blog posts and articles to videos and infographics, diverse and engaging content formats can drive engagement and improve search engine rankings.', title: 'Search Engine Optimization' }
        default: return { urlsrc: null, content: null, title: null }
    }
}